ALTER TABLE jobs ADD COLUMN IF NOT EXISTS output_url TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS r2_url TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_type TEXT DEFAULT 'video';
